version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.4.1
  slack: circleci/slack@6.1.3

executors:
  node:
    docker:
      - image: python:latest

references:
  workspace_root: &workspace_root ~/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

defaults: &defaults # Default directory to run the steps in.
  working_directory: *workspace_root

jobs:
  build_and_test:
    <<: *defaults
    docker:
      - image: khteh/ubuntu:latest
      - image: postgres:latest
        environment:
          POSTGRESQL_HOST: 127.0.0.1
          POSTGRESQL_DB: library
          POSTGRESQL_ALLOW_EMPTY_PASSWORD: true
          POSTGRESQL_USER: $DB_USERNAME
          POSTGRES_PASSWORD: $DB_PASSWORD
    #    restart: on-failure # Restart the container if it exits due to an error
    steps:
      - checkout:
          method: full
      - setup_remote_docker:
          docker_layer_caching: true
      #- run:
      #    name: install dockerize
      #    command: |
      #      DOCKERIZE_VERSION="v0.9.3"
      #      wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      - restore_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "uv.lock" }}
      - run: uv sync
      - run: uv pip install --group dev
      - run:
          name: Wait for PostgreSQL Server
          #command: dockerize -wait tcp://localhost:5432 -timeout 1m
          command: pg_isready -U "postgres" -h 127.0.0.1 -p 5432
      - run:
          name: Prepare database for tests
          command: |
            psql -h localhost -U postgres -c "CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD' ;"
            psql -h localhost -U postgres -c "CREATE DATABASE library WITH OWNER = $DB_USERNAME ;"
            psql -h localhost -U $DB_USERNAME -w -d library < library.sql
      #- run: uv run pytest -v Needs /etc/hypercorn.toml
      - run:
          name: Build docker image
          command: |
            VERSION=$(uv run python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])").$CIRCLE_BUILD_NUM
            docker build -t khteh/pythonrestapi:latest -t khteh/pythonrestapi:$VERSION .
      - run:
          name: Login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push images to docker hub
          command: |
            VERSION=$(uv run python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])").$CIRCLE_BUILD_NUM
            echo ${VERSION} > docker-build_number.txt
            docker push khteh/pythonrestapi:latest
            docker push khteh/pythonrestapi:$VERSION
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "uv.lock" }}
          paths:
            - /home/circleci/.local/bin
            - /home/circleci/.local/lib
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
  deploy-eks:
    executor: aws-cli/default
    <<: *defaults
    steps:
      - *attach_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Use the saved build number here
          command: |
            echo 'export CIRCLE_BUILD_NUM_DOCKER="$(cat docker-build_number.txt)"' >> $BASH_ENV
            . $BASH_ENV
            echo CIRCLE_BUILD_NUM_DOCKER: $CIRCLE_BUILD_NUM_DOCKER
      - run:
          name: Update Python RestAPI application
          command: |
            #kubectl patch statefulset pythonrestapi --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"'$AWS_ACCOUNT_ID'.dkr.ecr.ap-southeast-1.amazonaws.com/pythonrestapi:'$CIRCLE_BUILD_NUM_DOCKER'"}]'
            kubectl set image sts/pythonrestapi pythonrestapi=$AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/pythonrestapi:$CIRCLE_BUILD_NUM_DOCKER
  notification:
    docker:
      - image: "cimg/base:stable"
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS # context / project UI env-var reference
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  main:
    jobs:
      - build_and_test
#      - deploy-eks:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
#      - notification:
#          context: slack-secrets
#          name: BuyerPortal2.0
#          requires:
#            - BuildTestAndDeploy
