"""Add lastlogin field to user model

Revision ID: f5dadd6b2c17
Revises: c8fac49602e6
Create Date: 2021-09-29 12:01:17.576383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dadd6b2c17'
down_revision = 'c8fac49602e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastlogin', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastlogin')
    # ### end Alembic commands ###
